### ISSUE TITLE
Viewing logs

### ISSUE THREAD

**Issue by aqsede** [clifforama/multi-mount#1]
Hi, 

I just setup my home NAS and for some reason multi mount is not mounting into the mnt location. 
Is there any way I can view the logs and check any error output? 

My config: 
 mount_options="-t cifs -o vers=3.11,username=phone,password=SECRET"
 mount_source="//192.168.100.39/NAS"
 mount_target="/data/media/0/NFS_NAS"
 mount_max_retries=20
 mount_retry_interval=15s

I also tried with vers=2 same issues. Nothing is mounted. Any advice?

**Comment by ilham-Hamzah** [comment]
found it: https://topjohnwu.github.io/Magisk/guides.html
